### ISSUE TITLE
Separate AkibaKa?

### ISSUE THREAD

**Issue by andbits** [Akihabara/akihabara#1]
PotHix maybe you can turn AkibaKa into a submodule, would be easier for me to work on. =)

**Comment by PotHix** [comment]
It is already splitted to other repositories: https://github.com/Akihabara/experimental and https://github.com/Akihabara/demo-akibahero. I just removed "extras" folder from this repository. Thanks.

**Comment by andbits** [comment]
Ah OK, I was confused. Although maybe experimental should be renamed or something, it only has AkibaKa after all.

**Comment by PotHix** [comment]
I was talking to Kesiev about that and we will leave it with this name for now, and all experiments will go to this repository. If needed (or not used) we can change it later. :)

**Comment by andbits** [comment]
OK great, good to know. =D
